ResourcesGlobalization/ResourcesGlobalization.Mvc/Areas/Admin/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ResourcesGlobalization.Mvc.Areas.Admin.Controllers
{
    public class IndexController : Controller
    {
        // GET: Admin/Index
        public ActionResult Home()
        {
            return View();
        }
    }
}

ResourcesGlobalization/ResourcesGlobalization.Mvc/Areas/Admin/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace ResourcesGlobalization.Mvc.Areas.Admin.Controllers
{
    public class LanguageController : Controller
    {


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Change(String LanguageAbbrevation)
        {
            if (LanguageAbbrevation != null)
            {
                Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(LanguageAbbrevation);
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(LanguageAbbrevation);

            }

            HttpCookie cookie = new HttpCookie("Language");
            cookie.Value = LanguageAbbrevation;
            Response.Cookies.Add(cookie);

            return RedirectToAction("Home", "Index");
        }
    }
}

ResourcesGlobalization/ResourcesGlobalization.Mvc/Controllers/GlobalizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;

namespace ResourcesGlobalization.Mvc.Controllers
{
    public class GlobalizationController : Controller
    {
        // GET: Globalization
        [HttpGet]
        public ActionResult Index()
        {
            decimal valor = Convert.ToDecimal(4530.56);
            DateTime data = new DateTime(2017, 4, 21);

            var ciBr = new CultureInfo("pt-br");

            ViewBag.Valor = valor.ToString("c",ciBr);
            ViewBag.Data = data.ToString("D",ciBr);

            var ci = new CultureInfo("en-us");

            ViewBag.ValorUs = valor.ToString("c", ci);
            ViewBag.DataUs = data.ToString("D", ci);


            return View();
        }
    }
}

ResourcesGlobalization/ResourcesGlobalization.Mvc/Areas/Admin/Views/Index/Home.cshtml
@{
    ViewBag.Title = "Home";
}

<h2>Linguagens</h2>

<div class="container body-content">

    <ul>
        <li>@Html.ActionLink("English", "Change", "Language", new { LanguageAbbrevation = "en" }, null)</li>
        <li>@Html.ActionLink("Português", "Change", "Language", new { LanguageAbbrevation = "pt" }, null)</li>
        <li>@DateTime.Now.ToString()</li>
    </ul>
</div>

ResourcesGlobalization/ResourcesGlobalization.Mvc/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Multilinguagem", "Home", "Index", new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Globalization", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink(Resources.WebResources.linkSobre, "Home", "Index");
                    <li>@Html.ActionLink(Resources.WebResources.linkContato, "Home", "Index");
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Idioma
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Change", "Language", new { LanguageAbbrevation = "pt" },null)">Portugês</a></li>

                            <li><a href="@Url.Action("Change", "Language", new { LanguageAbbrevation = "en" },null)">Inglês</a></li>
                        </ul>
                    </li>
                  </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @Context.Application["app"]</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

ResourcesGlobalization/ResourcesGlobalization.Mvc/Views/Globalization/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm())
{
    <p>@Html.ActionLink(Resources.WebResources.mensagemInicial,"","", htmlAttributes: new {@class = "btn btn-link" })</p>
    <div class="container">
        <div class="panel">
            <h1 class="text-info">Exemplos de Globalization</h1>
            <br />
            <br />
            <p>Brasil</p>
                <label>@ViewBag.valor</label><br />  
                <label>@ViewBag.Data</label>
            <hr />
            <p>EUA</p>
                <label>@ViewBag.valorUs</label><br />
                <label>@ViewBag.DataUs</label>
        </div>
    </div>
}

ResourcesGlobalization/ResourcesGlobalization.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse  navbar-fixed-top" >
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Culture e Globalization", "Index", "Globalization", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Multilinguagem", "Home", "Index", new { area = "Admin" }, null)</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @Context.Application["app"]</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>